spec:
  replicas: 2
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: "-Xmx512m -Djava.net.preferIPv4Stack=true"
      imagePullSecrets:
      - name: dockerconfigjson